language: ruby
cache: bundler
rvm:
 - "2.0.0"


before_script:
  - psql -c 'create database smiling-wasabi_test;' -U postgres



notifications:
  email: false

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
