language: ruby
cache: bundler
rvm:
 - "2.0.0"


before_script:
  - psql -c 'create database smiling_wasabi_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

script:
  - bundle exec rake spec

bundler_args: --binstubs=./bundler_stubs

notifications:
  email: false

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
